### PR TITLE
Add gallery list

### PR DESCRIPTION
**Pull request by lucasbento**
This PR adds a gallery list & some minor improvements on the code.

[Demo](https://gifyu.com/image/Mjsm)

### CODE REVIEW

**Comment by lucasbento** [comment]
@Michaelvilleneuve: here's the option to either show or not the gallery list: https://github.com/Michaelvilleneuve/react-native-photo-gallery/pull/7/files#diff-168726dbe96b3ce427e7fedce31bb0bcR59

**Comment by Michaelvilleneuve** [comment]
I missed it indeed ! I just try it and merge :)

**Comment by Michaelvilleneuve** [comment]
Thank you very much !

**Comment by Michaelvilleneuve** [comment]
@lucasbento Don't hesitate to add a gif to README 👌

**Comment by lucasbento** [comment]
@Michaelvilleneuve: I'll send more PRs soon with code, gonna need more stuff with it.

We also need to update the README with the new props and class functions.

**Comment by Michaelvilleneuve** [comment]
Ok great :)

**Pull request merged**
